/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile"];
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions"];
        put?: never;
        /** Create Session */
        post: operations["create_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Settings */
        get: operations["get_my_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Settings */
        patch: operations["update_my_settings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateSessionIn */
        CreateSessionIn: {
            mode: components["schemas"]["PracticeMode"];
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "clarity" | "conciseness" | "structure" | "audience_fit" | "tone" | "confidence" | "grammar_vocabulary" | "fluency" | "pronunciation";
        /** EndSessionOut */
        EndSessionOut: {
            /** Report Status */
            report_status?: string | null;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * EnglishLevel
         * @enum {string}
         */
        EnglishLevel: "A2" | "B1" | "B2" | "C1" | "C2";
        /**
         * Goal
         * @enum {string}
         */
        Goal: "interviews" | "meetings" | "stakeholders" | "code_review" | "presentations" | "writing";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Llm
             * @enum {string}
             */
            llm: "ok" | "unavailable";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "unavailable";
        };
        /** HealthOut */
        HealthOut: {
            checks: components["schemas"]["HealthChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** MeOut */
        MeOut: {
            profile: components["schemas"]["ProfileOut"];
            settings: components["schemas"]["SettingsOut"];
            user: components["schemas"]["UserOut"];
        };
        /** MessageOut */
        MessageOut: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["MessageRole"];
            /** Seq */
            seq: number;
            source: components["schemas"]["MessageSource"];
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "assistant" | "user";
        /**
         * MessageSource
         * @enum {string}
         */
        MessageSource: "text" | "voice" | "system";
        /** Page[SessionSummary] */
        Page_SessionSummary_: {
            /** Items */
            items: components["schemas"]["SessionSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * Persona
         * @description The AI character in a practice scenario (`scenarios.persona`).
         */
        Persona: {
            /** Goals */
            goals: string;
            /** Name */
            name: string;
            /** Personality */
            personality: string;
            /** Role */
            role: string;
        };
        /**
         * PracticeMode
         * @enum {string}
         */
        PracticeMode: "text" | "voice";
        /** ProfileOut */
        ProfileOut: {
            /** Display Name */
            display_name: string;
            english_level: components["schemas"]["EnglishLevel"];
            /** Focus Areas */
            focus_areas: components["schemas"]["Dimension"][];
            /** Goals */
            goals: components["schemas"]["Goal"][];
            /** Native Language */
            native_language: string | null;
            seniority: components["schemas"]["Seniority"];
            /** Timezone */
            timezone: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            english_level?: components["schemas"]["EnglishLevel"] | null;
            /** Focus Areas */
            focus_areas?: components["schemas"]["Dimension"][] | null;
            /** Goals */
            goals?: components["schemas"]["Goal"][] | null;
            /** Native Language */
            native_language?: string | null;
            seniority?: components["schemas"]["Seniority"] | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * RecommendedMode
         * @enum {string}
         */
        RecommendedMode: "text" | "voice" | "either";
        /**
         * ScenarioCategory
         * @enum {string}
         */
        ScenarioCategory: "status_updates" | "stakeholder_communication" | "interviews" | "code_review" | "negotiation" | "meetings" | "career";
        /** ScenarioDetail */
        ScenarioDetail: {
            category: components["schemas"]["ScenarioCategory"];
            /** Difficulty */
            difficulty: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Custom */
            is_custom: boolean;
            /** Opening Line */
            opening_line: string;
            persona: components["schemas"]["Persona"];
            recommended_mode: components["schemas"]["RecommendedMode"];
            /** Slug */
            slug: string;
            /** Success Criteria */
            success_criteria: string[];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** User Objective */
            user_objective: string;
        };
        /** ScenarioRef */
        ScenarioRef: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            category: components["schemas"]["ScenarioCategory"];
            /** Difficulty */
            difficulty: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Custom */
            is_custom: boolean;
            recommended_mode: components["schemas"]["RecommendedMode"];
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "junior" | "mid" | "senior" | "staff_plus" | "manager";
        /** SessionDetail */
        SessionDetail: {
            /** Ended At */
            ended_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            limits: components["schemas"]["SessionLimits"];
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            mode: components["schemas"]["PracticeMode"];
            /** Overall Score */
            overall_score?: number | null;
            scenario: components["schemas"]["ScenarioRef"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /** User Turns */
            user_turns: number;
        };
        /** SessionLimits */
        SessionLimits: {
            /** Max Message Chars */
            max_message_chars: number;
            /** Max User Turns */
            max_user_turns: number;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "active" | "ended" | "abandoned";
        /** SessionSummary */
        SessionSummary: {
            /** Ended At */
            ended_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            mode: components["schemas"]["PracticeMode"];
            /** Overall Score */
            overall_score?: number | null;
            scenario: components["schemas"]["ScenarioRef"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /** User Turns */
            user_turns: number;
        };
        /** SettingsOut */
        SettingsOut: {
            default_mode: components["schemas"]["PracticeMode"];
            /** Tts Voice */
            tts_voice: string;
            voice_input_mode: components["schemas"]["VoiceInputMode"];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            default_mode?: components["schemas"]["PracticeMode"] | null;
            /** Tts Voice */
            tts_voice?: string | null;
            voice_input_mode?: components["schemas"]["VoiceInputMode"] | null;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Local */
            is_local: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceInputMode
         * @enum {string}
         */
        VoiceInputMode: "push_to_talk" | "hands_free";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    update_my_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios: {
        parameters: {
            query?: {
                category?: components["schemas"]["ScenarioCategory"] | null;
                difficulty?: number | null;
                mode?: components["schemas"]["RecommendedMode"] | null;
                owner?: "builtin" | "mine" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: components["schemas"]["SessionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_my_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
