/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile"];
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Settings */
        get: operations["get_my_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Settings */
        patch: operations["update_my_settings"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "clarity" | "conciseness" | "structure" | "audience_fit" | "tone" | "confidence" | "grammar_vocabulary" | "fluency" | "pronunciation";
        /**
         * EnglishLevel
         * @enum {string}
         */
        EnglishLevel: "A2" | "B1" | "B2" | "C1" | "C2";
        /**
         * Goal
         * @enum {string}
         */
        Goal: "interviews" | "meetings" | "stakeholders" | "code_review" | "presentations" | "writing";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthChecks */
        HealthChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Llm
             * @enum {string}
             */
            llm: "ok" | "unavailable";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "unavailable";
        };
        /** HealthOut */
        HealthOut: {
            checks: components["schemas"]["HealthChecks"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** MeOut */
        MeOut: {
            profile: components["schemas"]["ProfileOut"];
            settings: components["schemas"]["SettingsOut"];
            user: components["schemas"]["UserOut"];
        };
        /**
         * PracticeMode
         * @enum {string}
         */
        PracticeMode: "text" | "voice";
        /** ProfileOut */
        ProfileOut: {
            /** Display Name */
            display_name: string;
            english_level: components["schemas"]["EnglishLevel"];
            /** Focus Areas */
            focus_areas: components["schemas"]["Dimension"][];
            /** Goals */
            goals: components["schemas"]["Goal"][];
            /** Native Language */
            native_language: string | null;
            seniority: components["schemas"]["Seniority"];
            /** Timezone */
            timezone: string;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Display Name */
            display_name?: string | null;
            english_level?: components["schemas"]["EnglishLevel"] | null;
            /** Focus Areas */
            focus_areas?: components["schemas"]["Dimension"][] | null;
            /** Goals */
            goals?: components["schemas"]["Goal"][] | null;
            /** Native Language */
            native_language?: string | null;
            seniority?: components["schemas"]["Seniority"] | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "junior" | "mid" | "senior" | "staff_plus" | "manager";
        /** SettingsOut */
        SettingsOut: {
            default_mode: components["schemas"]["PracticeMode"];
            /** Tts Voice */
            tts_voice: string;
            voice_input_mode: components["schemas"]["VoiceInputMode"];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            default_mode?: components["schemas"]["PracticeMode"] | null;
            /** Tts Voice */
            tts_voice?: string | null;
            voice_input_mode?: components["schemas"]["VoiceInputMode"] | null;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Local */
            is_local: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceInputMode
         * @enum {string}
         */
        VoiceInputMode: "push_to_talk" | "hands_free";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    update_my_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_my_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
