"""users profiles settings

Revision ID: 0001
Revises:
Create Date: 2026-09-17 03:51:25.851833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_local", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), server_default="You", nullable=False),
        sa.Column(
            "seniority",
            sa.Enum(
                "junior",
                "mid",
                "senior",
                "staff_plus",
                "manager",
                name="seniority",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="mid",
            nullable=False,
        ),
        sa.Column("native_language", sa.Text(), nullable=True),
        sa.Column(
            "english_level",
            sa.Enum(
                "A2",
                "B1",
                "B2",
                "C1",
                "C2",
                name="english_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="B2",
            nullable=False,
        ),
        sa.Column("goals", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "focus_areas", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "default_mode",
            sa.Enum(
                "text",
                "voice",
                name="default_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="text",
            nullable=False,
        ),
        sa.Column(
            "voice_input_mode",
            sa.Enum(
                "push_to_talk",
                "hands_free",
                name="voice_input_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="push_to_talk",
            nullable=False,
        ),
        sa.Column("tts_voice", sa.Text(), nullable=False),
        sa.Column(
            "reminders_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("reminder_time", sa.Time(), nullable=True),
        sa.Column(
            "weekly_summary_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    op.drop_table("profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
