"""scenarios

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17 18:57:16.296187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "status_updates",
                "stakeholder_communication",
                "interviews",
                "code_review",
                "negotiation",
                "meetings",
                "career",
                name="category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("persona", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_objective", sa.Text(), nullable=False),
        sa.Column("opening_line", sa.Text(), nullable=False),
        sa.Column("success_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recommended_mode",
            sa.Enum(
                "text",
                "voice",
                "either",
                name="recommended_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "keyterms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("rubric_version", sa.Text(), server_default="v1", nullable=False),
        sa.Column("is_assessment", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_custom", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty BETWEEN 1 AND 3", name=op.f("ck_scenarios_difficulty_range")
        ),
        sa.CheckConstraint(
            "is_custom = (owner_user_id IS NOT NULL)", name=op.f("ck_scenarios_custom_has_owner")
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_scenarios_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
        sa.UniqueConstraint("slug", name=op.f("uq_scenarios_slug")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenarios")
    # ### end Alembic commands ###
