"""Business limits shared across the API (product-spec §5)."""

MAX_USER_TURNS = 20
MAX_MESSAGE_CHARS = 1000
MIN_USER_TURNS_FOR_REPORT = 2
VOICE_SESSION_MAX_SECONDS = 1200
VOICE_TURN_MAX_SECONDS = 90
PRONUNCIATION_MAX_SECONDS = 30
DRILL_AUDIO_MAX_SECONDS = 90
MAX_ACTIVE_COACH_NOTES = 8
DRILLS_PER_DAY = 3
